### ISSUE TITLE
Why separate field type and format?

### ISSUE THREAD

**Issue by da4089** [finspec/finspec-spec#11]
Field types: integer, char, string, etc, are augmented with a format: int8, int16, etc, in order to provide additional information about their representation.

What's the benefit of splitting this specification into two (and perhaps three with endianness)?

It would be more succinct to have a single, fully-specified field type.  This would basically reflect the current format, and would imply the semantics currently encoded by the type.

**Comment by mahenpatil** [comment]
Included in v0.2.
