### ISSUE TITLE
Allow specification of legal range of numeric fields

### ISSUE THREAD

**Issue by da4089** [finspec/finspec-spec#14]
In some cases, the allowed range of values for a numeric field is specified to be less than that possible for its on-the-wire representation, eg. NASDAQ OUCH number of shares in an order is limited to 1,000,000 despite being a uint32 datatype.

We should allow specification of range limits to support this usage.

As a suggestion, we could reuse the JSON-Schema mechanism: "minimum", "maximum", "exclusiveMinimum" and "exclusiveMaximum" properties for the field object, valid when its type is numeric:  integer, float, and (ideally) string-with-integer-extended-type.

**Comment by mahenpatil** [comment]
Covered in 0.2.
