### ISSUE TITLE
No way to specify endianness of numerical types

### ISSUE THREAD

**Issue by da4089** [finspec/finspec-spec#2]
Sizes for numerical types are defined, but not endianness.
Some binary protocols use big-endian, some use little-endian.

**Comment by da4089** [comment]
Some options:

- different _format_ specifiers for fields: _int8be_ or _int8le_ instead of _int8_,
- an optional _endianness_ property for fields, in addition to _type_ and _format_, with values _little_ or _big_ (let's hope we can avoid _vax_)
- an optional _endianness_ property for _sessionMessages_, which controls the format for all integers (would probably need a per-field property to override this too, but it'd avoid a lot of verbosity in the usual case).

**Comment by CJLees01** [comment]
Have you ever observed a mixture of big and little endianness within a single specification? So far, we've only seen entire specs with one or the other endianness, and all numeric types follow that.

If I'm correct in that, could we have a single endianness field (within the `properties` block) that applies for the whole spec?

**Comment by da4089** [comment]
I vaguely recall one instance where this was the case, but I cannot remember (or find) what it was now.  It's likely that it's no longer that way anyway.  My feeling is that it was big-endian in a SOUP-like encapsulation, but little-endian in the application messages, but none of the specs I've checked are like that.

So ... I think it'd make sense to have a default for the whole specification, but it seems a little optimistic to assume that will always work, especially since there doesn't seem to be a good way (yet?) to layer things like SOUP and OUCH.  I'd like to see an exception mechanism available, in case it's required.

**Comment by mahenpatil** [comment]
Included in v0.2. (Default endianness can be defined at the top level. Can define separate datatype for exceptional fields).
