### ISSUE TITLE
Specification of legal ordering of messages?

### ISSUE THREAD

**Issue by da4089** [finspec/finspec-spec#3]
It'd be great to support a specification of the possible ordering of messages within a valid protocol stream.

eg. Logon before application messages; request -> reply expectations; etc.

**Comment by finspec** [comment]
Thanks for the suggestion, it's in our pipeline already.

**Comment by da4089** [comment]
Great!

Perhaps you could either put your existing roadmap in the repo's wiki, or publish whatever drafts you have?  That'd avoid most issues like this in future ...

**Comment by mahenpatil** [comment]
Chris has already shared drafts for Conditional Fields and Workflow. Need to take if forward to specify the ordering of messages as well.

We also have been toying with the idea of specifying the state diagram in the specifications which can be consumed by the visual specification editor/viewer to display the state diagrams similar to what we have in lot many pdfs. This too shall help the cause of expressing the ordering of messages.
