### ISSUE TITLE
Implied decimal precision for binary protocols

### ISSUE THREAD

**Issue by CJLees01** [finspec/finspec-spec#6]
Binary procotols typically represent decimal or float datatypes (eg price) as int32 or int64, with an implied number of decimal places. For example LSE define two such datatypes:

Float (int32) - Signed little-endian encoded four byte integer field with four implied decimal places.
Price (int64) - Signed little-endian encoded eight byte integer field with eight implied decimal places.

We need a mechanism for capturing the implied number of decimals. Some suggestions:

1. Support an optional `decimals` field at the field properties level (absence indicates this is an integer):
`{...
      "type": "integer",
      "format": "int64",
      "decimals": 8,
...},`

2. To allow re-use define a `datatypes` block at the top-level, to define all datatypes for the spec in a single location, and then reference this from each field. This follows current PDF convention, although is arguably more geared to human readers than machines.

**Comment by mahenpatil** [comment]
Included in v0.2.
