### ISSUE TITLE
Timestamp precision for binary protocols

### ISSUE THREAD

**Issue by CJLees01** [finspec/finspec-spec#7]
Binary procotols typically represent timestamps in an entirely inconsistent way - strings, timestamps or integers (with an implied sequence of milli / micro / nano seconds). Examples:

NASDAQ GLIMPSE: 6-byte integer representing nanoseconds past midnight
BATS BOE: int64 representing nanoseconds since epoch (with nanoseconds currently set to zero)
LSE Native (I): ExpireDateTime is int32 representing seconds since epoch (excluding leap seconds)
LSE Native (II): TransactTime is actually two int32 next to each other; the first representing seconds since epoch (excluding leap seconds), and the second is microseconds.

We need a mechanism for codifying the different approach for time granularity. Some suggestions:

1. Support an optional `timeFormat` field property with options of `seconds`,`milli`,`micro`,`nano` (absence indicates seconds). BATS BOE would then become:

    {... "type": "integer", "format": "int64", "timeFormat": "nano", ...},

2. Create a datatypes block at the top-level, to define all datatypes for the spec in a single location, and then reference this from each field. (Same idea as issue #6 )

**Comment by mahenpatil** [comment]
Included in v0.2.
