### ISSUE TITLE
Mechanism for indicating field padding in  fixed-length fields

### ISSUE THREAD

**Issue by CJLees01** [finspec/finspec-spec#8]
In fixed-width protocols, empty fields must be padded to the required width. We need a mechanism for conveying both the side and character used for padding. Some suggestions:

1. Add optional definitions of `padChar` and `padSide` (with valid values of `left` and `right`) to the fields definition. Absence of these fields should imply space-padded to the left. For example an integer to be zero-padded to the left up would appear as:

`{..."alwaysRequired": true, "type": "string", "length": 25, "padChar": "0", "padSide": "left"...}

2. If we define a common `datatypes` block, the default `padChar` and `padSide` values can be defined centrally and understood to apply to all fields of that datatype in the spec. (See #6 )

**Comment by mahenpatil** [comment]
Included in v0.2.
